### ISSUE TITLE
merge manifest bundles

### ISSUE THREAD

**Issue by stzb321** [studentutu/MergeAssetBundleManifests#1]
hi, i am looking for a solution that can merge manifest bundles into one manifest bundle(the file without ".manifest" extension)
its very similar to this repo
any idea will appreciated

**Comment by stzb321** [comment]
i have found a solution

**Comment by studentutu** [comment]
@stzb321  could you share it?

**Comment by stzb321** [comment]
> @stzb321 could you share it?

Yes.
1. use **EditorJsonUtility.ToJson** to transfer manifest objs to json string
2. there are many way can merge json you can find out
3. use  **EditorJsonUtility.FromJsonOverwrite** to transfer the merged json string to a merged manifest obj
4. pack the merged manifest obj into assetbundle
